<a href="https://colab.research.google.com/github/eugeniaring/machine-learning-course-eugenia/blob/main/lezione1_basipython_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip list

Package                          Version
-------------------------------- ---------------------
absl-py                          1.4.0
aiohttp                          3.8.5
aiosignal                        1.3.1
alabaster                        0.7.13
albumentations                   1.3.1
altair                           4.2.2
anyio                            3.7.1
appdirs                          1.4.4
argon2-cffi                      23.1.0
argon2-cffi-bindings             21.2.0
array-record                     0.4.1
arviz                            0.15.1
astropy                          5.3.4
astunparse                       1.6.3
async-timeout                    4.0.3
attrs                            23.1.0
audioread                        3.0.1
autograd                         1.6.2
Babel                            2.13.0
backcall                         0.2.0
beautifulsoup4                   4.11.2
bleach                           6.0.0
blinker                          1.4
bl

# Basi di Pyhon

### Interi

In [ ]:
x = 5

In [ ]:
x

5

In [ ]:
type(x)

int

## float

In [ ]:
y = 4.5

In [ ]:
type(y)

float

In [ ]:
y = 4,5

In [ ]:
y

(4, 5)

## stringa

In [ ]:
s1 = "eugenia"

In [ ]:
s1 = 'eugenia'

In [ ]:
s1

'eugenia'

In [ ]:
s1[0] = 'r'

TypeError: ignored

In [ ]:
s2 = s1.upper()
s2

'EUGENIA'

In [ ]:
s1[1]

'u'

 ## booleano

In [ ]:
b1 = True

In [ ]:
b1

True

In [ ]:
type(b1)

bool

## lista

In [ ]:
l = [1,2,3,4]

In [ ]:
type(l)

list

In [ ]:
l[-1]

4

In [ ]:
l[0] = [5,6,7]

In [ ]:
l.append(8)

In [ ]:
l

[3, 4, 5, 5, 8]

In [ ]:
l.extend([9,10])

In [ ]:
l

[3, 4, 5, 5, 8, 9, 10]

In [ ]:
l = [3,4,5,5]

In [ ]:
set(l)

{3, 4, 5}

## dizionario

In [ ]:
d = {'nome':['Lucia','Sara'],'cognome':['Ba','LE']}

In [ ]:
d['cognome'][1]

'LE'

In [ ]:
d['numero_telefono'] = [345555555,36788888888]

In [ ]:
d

{'nome': ['Lucia', 'Sara'],
 'cognome': ['Ba', 'LE'],
 'numero_telefono': [345555555, 36788888888]}

In [ ]:
d['nome']

['Lucia', 'Sara']

In [ ]:
d.keys()

dict_keys(['nome', 'cognome'])

In [ ]:
d.values()

dict_values([['Lucia', 'Sara'], ['Ba', 'LE']])

## if else

In [ ]:
pari = True
if pari == True:
  print('Ciao!')

Ciao!


In [ ]:
num = 7
if num > 0:
  print('Numero positivo')
else:
  print('Numero negativo')

Numero positivo


In [ ]:
x = 5
y = 8

if x == y:
  print('sono uguali')
elif x>y:
  print('x maggiore di y')
else:
  print('x minore di y')

x minore di y


## for loop

In [ ]:
l = [3,4,5,6]
for el in l:
   print(el)

3
4
5
6


In [ ]:
v_6 = 4

In [ ]:
l = [2,3]

[3, 4, 5, 6]

In [ ]:
s = 0
for l2 in l:
  s = s + l2 # s = 2  # s = 2+3

In [ ]:
s

18

In [ ]:
len(l)

4

In [ ]:
l

[3, 4, 5, 6]

In [ ]:
l.remove(5)

In [ ]:
l

[3, 4, 6]

In [ ]:
l.pop(0)

3

In [ ]:
l

[4, 6]

## while loop

In [ ]:
i = 0
while i < 6:
  print(i)
  i = i+1

0
1
2
3
4
5


In [ ]:
l = [3,4,5,6]

In [ ]:
i = 0
while i < 3:
   print(l[i])
   i += 1

3
4
5


In [ ]:
lista = [1,2,3]

[3, 4, 5, 6]

## function

In [ ]:
def calcola_media(l):
    somma = 0
    for el in l:
       somma += el #3 #3+4 = 7
    media = somma/len(l)
    return media

In [ ]:
calcola_media(l=lista)

In [ ]:
list(range(7))

[0, 1, 2, 3, 4, 5, 6]

In [ ]:
list(range(0,7))

[0, 1, 2, 3, 4, 5, 6]

In [ ]:
list(range(1,7))

[1, 2, 3, 4, 5, 6]

In [ ]:
list(range(2,7,2))

[2, 4, 6]

In [ ]:
lista = [2,3,4]

In [ ]:
def calcola_media(l):
   # definisco che la variabile è uguale a 0
    somma = 0
    for i in range(len(l)-1):
       somma += l[i]
    return somma

In [ ]:
calcola_media(lista)

5

In [ ]:
for i in range(len(lista)-1):
  print(i)

0
1


In [ ]:
import math as m

In [ ]:
num = 16
m.sqrt(num)

4.0

In [ ]:
math.pi

3.141592653589793

In [ ]:
math.pow(2,3)

8.0

# array

## lista vs numpy array

In [ ]:
l1 = [3,4,5,6]
l2 = [1,1,1,1]
l1+l2

[3, 4, 5, 6, 1, 1, 1, 1]

In [ ]:
l1*2

[3, 4, 5, 6, 3, 4, 5, 6]

In [ ]:
l2*3

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [ ]:
len(l1)

4

In [ ]:
l1

[3, 4, 5, 6]

In [ ]:
l2

[1, 1, 1, 1]

In [ ]:
l_somma = []

for i in range(len(l1)): # for i in [0,1,2,3]
   l_somma.append(l1[i]+l2[i]) # step 1 - l_somma = [4]
                               # step 2 - l_somma = [4,5]
                               # step 3 - l_somma = [4,5,6]
                               # step 4 - l_somma = [4,5,6,7]

print(l_somma)

[4, 5, 6, 7]


In [ ]:
l1 = [[2,3],0]

In [ ]:
l2 = [[2,3],1]

In [ ]:
[ l1[i]+l2[i] for i in range(len(l1))]

[[2, 3, 2, 3], 1]

In [ ]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [ ]:
[i for i in range(6)]

[0, 1, 2, 3, 4, 5]

In [ ]:
l1+l2

[3, 4, 5, 6, 1, 1, 1, 1]

In [ ]:
import numpy as np

## creare array

In [ ]:
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
a2 = np.zeros()
a2

TypeError: ignored

In [ ]:
a1 = np.ones((5,3),dtype=np.int8)
a1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [ ]:
a1 = np.ones((5,3),dtype=np.int8)
a1

In [ ]:
a_identity = np.identity(4)
a_identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [ ]:
np.random.randint(1,7,(4,3))

array([[4, 4, 3],
       [4, 3, 3],
       [6, 4, 4],
       [5, 3, 3]])

In [ ]:
np.random.random_sample(6)

array([0.68542079, 0.56847456, 0.48091363, 0.86133538, 0.45113043,
       0.29560778])

In [ ]:
l1 = [1,2,3]
l2 = [1,1,1]
l1+l2

[1, 2, 3, 1, 1, 1]

In [ ]:
l1*l2

TypeError: ignored

In [ ]:
a1 = np.array([1,2,3])
a2 = np.array([1,1,1])
a1+a2

array([2, 3, 4])

In [ ]:
a1*2

array([2, 4, 6])

In [ ]:
a1

array([1, 2, 3])

In [ ]:
a2

array([1, 1, 1])

In [ ]:
a1*a2

array([1, 2, 3])

In [ ]:
a1 = np.ones((3,4))
a1*4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [ ]:
a1 = np.ones((2,3))
a2 = np.array([1])
a1*a2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
a10 = np.full((3,3),10)
print(a10)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [ ]:
a10 = np.full((3,3),7)
print(a10)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
type(a10)

numpy.ndarray

In [ ]:
a10.shape

(3, 3)

In [ ]:
lista = [[3,4],[4,5]]

In [ ]:
lista[0][1]

4

In [ ]:
array2 = np.array(lista)
array2[0][1]

4

In [ ]:
array2[0,1]

4

In [ ]:
l = [1,2,3,4,5,6,7]


## slicing

In [ ]:
l[0:2]

[1, 2]

In [ ]:
l[:2]

[1, 2]

In [ ]:
l[3:]

[4, 5, 6, 7]

In [ ]:
a2 = np.array([1,2,3,4],[5,6,7,8])

In [ ]:
a2[:3]

array([1, 2, 3])

In [ ]:
l4 = [[2,3,4,5,6],[4,5,7,8,9]]
l4

[[2, 3, 4, 5, 6], [4, 5, 7, 8, 9]]

In [ ]:
a4 = np.array([[2,3,4,5,6],[4,5,7,8,9]])

In [ ]:
a4[0,0]

array([[2, 3, 4, 5, 6],
       [4, 5, 7, 8, 9]])

In [ ]:
a4[0,0]

2

In [ ]:
a4[0,0]

In [ ]:
a4[1,0]

4

In [ ]:
a4[1,1]

5

In [ ]:
a4[:,0:2]

array([[2, 3],
       [4, 5]])

In [ ]:
a4

array([[2, 3, 4, 5, 6],
       [4, 5, 7, 8, 9]])

In [ ]:
a4[:,0:3]

array([[2, 3, 4],
       [4, 5, 7]])

In [ ]:
a4[0:2,:]

array([[2, 3, 4, 5, 6],
       [4, 5, 7, 8, 9]])

In [ ]:
a3 = np.zeros((3,4))

In [ ]:
a3.shape

(3, 4)

In [ ]:
a3 = a3.reshape((2,6))
a3.shape

(2, 6)

In [ ]:
l = [1,2,3,4]

In [ ]:
min(l)

1

In [ ]:
max(l)

4

In [ ]:
a3 = np.array([1,2,3,4])

## funzioni matematiche di numpy

In [ ]:
np.max(a3)

4

In [ ]:
np.argmax(a3)

3

In [ ]:
np.min(a3)

1

In [ ]:
np.argmin(a3)

0

In [ ]:
np.mean(a3)

2.5

In [ ]:
np.median(a3)

2.5

In [ ]:
np.var(a3)

1.25

In [ ]:
a5 = np.array([7,2,6,9,1])

In [ ]:
a5.sort()

In [ ]:
a5

array([1, 2, 6, 7, 9])

In [ ]:
l = [7,2,6,9,1]

In [ ]:
sorted(l,reverse=True)

[9, 7, 6, 2, 1]

In [ ]:
# indici dei valori in ordine
np.argsort(a5)

array([0, 1, 2, 3, 4])

In [ ]:
a5

array([1, 2, 6, 7, 9])

In [ ]:
a5.sum()

25

In [ ]:
a2d = np.array([[2,3,4],[5,6,7]])
np.min(a2d)

2

In [ ]:
np.min(a2d,axis=1)

array([2, 5])

In [ ]:
np.min(a2d,axis=0)

array([2, 3, 4])

In [ ]:
for el in a2d:
   print(el)
   print(type(el))

[2 3 4]
<class 'numpy.ndarray'>
[5 6 7]
<class 'numpy.ndarray'>


In [ ]:
# filtraggio

a2d[a2d == 7]

array([7])

In [ ]:
a2d[a2d < 4]

array([2, 3])

In [ ]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a3 = np.array([[4,5,9],[6,9,0]])

In [ ]:
a3

array([[4, 5, 9],
       [6, 2, 9]])

In [ ]:
np.max(a3)

9

In [ ]:
a3[0][2]

9

In [ ]:
a3[1][1]

9

In [ ]:
np.argmax(a3)

2

In [ ]:
a3

array([[4, 5, 9],
       [6, 9, 0]])

In [ ]:
np.argmax(a3,axis=1)

array([2, 1])

In [ ]:
np.argmax(a3,axis=0)

array([1, 1, 0])

In [ ]:
a3

array([[4, 5, 9],
       [6, 9, 0]])

In [ ]:
a3[:,0:2]

array([[4, 5],
       [6, 9]])

In [ ]:
a3[a3>5]

array([9, 6, 9])

In [ ]:
a3[a3%2==0]

array([4, 6, 0])

In [ ]:
a3

array([[4, 5, 9],
       [6, 9, 0]])

In [ ]:
np.sort(a3)

array([[4, 5, 9],
       [0, 6, 9]])

In [ ]:
a3.shape

(2, 3)

In [ ]:
a4 = a3.reshape(6)
print(a4)
print(a4.shape)

[4 5 9 6 9 0]
(6,)


In [ ]:
a3 = np.array([[4, 5, 9],[0, 6, 9]])

In [ ]:
a4 = a3.reshape(6,1)
print(a4)
print(a4.shape)

[[4]
 [5]
 [9]
 [0]
 [6]
 [9]]
(6, 1)


In [ ]:
a3 = np.array([[4, 5, 9],[0, 6, 9]])
a4 = np.array([[4, 5, 9],[0, 6, 9]])

In [ ]:
a3 + a4

array([[ 8, 10, 18],
       [ 0, 12, 18]])

In [ ]:
a3 * a4

array([[16, 25, 81],
       [ 0, 36, 81]])

In [ ]:
np.log(a3)

<ipython-input-264-04f6e631047e>:1: RuntimeWarning: divide by zero encountered in log
  np.log(a3)


array([[1.38629436, 1.60943791, 2.19722458],
       [      -inf, 1.79175947, 2.19722458]])

In [ ]:
np.sqrt(a3)

array([[2.        , 2.23606798, 3.        ],
       [0.        , 2.44948974, 3.        ]])

In [ ]:
diz = {'a':[3,4,5],'b':[6,7]}

In [ ]:
diz['b']

[6, 7]

In [ ]:
diz.keys()

dict_keys(['a', 'b'])

In [ ]:
diz.values()

dict_values([[3, 4, 5], [6, 7]])

In [ ]:
diz['c'] = [1,2]

In [ ]:
diz

{'a': [3, 4, 5], 'b': [6, 7], 'c': [1, 2]}